CREATE TABLE Homework (
    id INT generated by default as identity  PRIMARY KEY,
    name varchar(255),
    description varchar(255)
);

CREATE TABLE Lesson (
    id INT generated by default as identity  PRIMARY KEY,
    name varchar(255),
    updatedAt timestamp default now(),
	homework_id INT,
    CONSTRAINT fk_homework foreign key(homework_id) references HOMEWORK(ID)
);

CREATE TABLE Schedule (
    id INT generated by default as identity  PRIMARY KEY,
    updatedAt timestamp default now()
);

CREATE TABLE schedule_lesson (
    schedule_lesson_id INT generated by default as identity  PRIMARY KEY,
    schedule_id INT not null,
    lesson_id INT not null,
    CONSTRAINT fk_schedule foreign key(schedule_id) references schedule(ID),
    CONSTRAINT fk_lesson foreign key(lesson_id) references lesson(ID)
);