CREATE TABLE Homework (
    id INT generated by default as identity  PRIMARY KEY,
    name varchar(255),
    description varchar(255)
);

CREATE TABLE Lesson (
    id INT generated by default as identity  PRIMARY KEY,
    name varchar(255),
    updatedAt timestamp default now(),
	homework_id INT,
    CONSTRAINT fk_homework foreign key(homework_id) references HOMEWORK(ID)
);

CREATE TABLE Schedule (
    id INT generated by default as identity  PRIMARY KEY,
    name varchar(255),
    updatedAt timestamp default now()
);

CREATE TABLE schedule_lesson (
    schedule_lesson_id INT generated by default as identity  PRIMARY KEY,
    schedule_id INT not null,
    lesson_id INT not null,
    CONSTRAINT fk_schedule foreign key(schedule_id) references schedule(ID),
    CONSTRAINT fk_lesson foreign key(lesson_id) references lesson(ID)
);

CREATE TABLE Hero (
    id INT generated by default as identity  PRIMARY KEY,
    name varchar(255),
    gender varchar(255),
    eyeColor varchar(255),
    race varchar(255),
    hairColor varchar(255),
    height double precision,
    publisher varchar(255),
    skinColor varchar(255),
    alignment varchar(255),
    weight INT
);

create table heroes_information(
    id INT generated by default as identity  PRIMARY KEY,
    name varchar(255),
    gender varchar(255),
    eyeColor varchar(255),
    race varchar(255),
    hairColor varchar(255),
    height varchar(255),
    publisher varchar(255),
    skinColor varchar(255),
    alignment varchar(255),
    weight INT
);

CREATE TABLE users (
    id INT generated by default as identity  PRIMARY KEY,
    uid varchar(255) UNIQUE,
    name varchar(255),
    email varchar(255) UNIQUE,
    role varchar(255)
);